name: Create release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mac:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v1
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - run: npm run package
    - run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
          # Artifact name
          name: macos
          path: out
  linux:
    runs-on: [self-hosted, linux]
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v1
    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - run: npm run test
    - run: npm run package
    - run: npm run make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
          # Artifact name
          name: ubuntu
          path: out